/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package greenplanet.gui;

/**
 *
 * @author JLou
 */
public class AfterGamePanel extends javax.swing.JPanel {

    /**
     * Creates new form AfterGamePanel
     */
    public AfterGamePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        TurnByTurnPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TurnByTurnPanel.setLayout(new javax.swing.BoxLayout(TurnByTurnPanel, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(69, 60));
        jPanel1.setMinimumSize(new java.awt.Dimension(69, 60));
        jPanel1.setPreferredSize(new java.awt.Dimension(69, 60));

        jLabel1.setText("Tour ");
        jPanel1.add(jLabel1);
        jPanel1.add(jSpinner1);

        TurnByTurnPanel.add(jPanel1);

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jLabel2.setText("FAUT BOSSER PDS");
        jTabbedPane2.addTab("Repartition Energies", jLabel2);

        jLabel3.setText("FAUT BOSSER PDS");
        jTabbedPane2.addTab("Batiments", jLabel3);

        jLabel4.setText("FAUT BOSSER PDS");
        jTabbedPane2.addTab("Production Energie", jLabel4);

        jLabel5.setText("FAUT BOSSER PDS");
        jTabbedPane2.addTab("DUNNO", jLabel5);

        TurnByTurnPanel.add(jTabbedPane2);

        jTabbedPane1.addTab("Tour par Tour", TurnByTurnPanel);

        jTabbedPane3.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jLabel6.setText("12->15");
        jTabbedPane3.addTab("Prix Energie", jLabel6);

        jLabel7.setText("12->15");
        jTabbedPane3.addTab("Prod", jLabel7);

        jLabel8.setText("12->15");
        jTabbedPane3.addTab("XXX", jLabel8);

        jLabel9.setText("12->15");
        jTabbedPane3.addTab("YY", jLabel9);

        jLabel10.setText("12->15");
        jTabbedPane3.addTab("Z", jLabel10);

        jTabbedPane1.addTab("Overview", jTabbedPane3);

        add(jTabbedPane1);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TurnByTurnPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    // End of variables declaration//GEN-END:variables
}
