/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package greenplanet.gui;

/**
 *
 * @author JLou
 */
public class OnlineOptionsPanel extends javax.swing.JPanel {

    /**
     * Creates new form OnlineOptionsPanel
     */
    public OnlineOptionsPanel() {
        initComponents();
        
        startGameButton.addMouseListener(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        playerNameField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        gameNumberSpinner = new javax.swing.JSpinner();
        startGameButton = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel1.setText("Nom du joueur");
        jPanel1.add(jLabel1);

        playerNameField.setText("jTextField1");
        playerNameField.setPreferredSize(new java.awt.Dimension(206, 20));
        playerNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(playerNameField);

        add(jPanel1);

        jLabel2.setText("Numero de partie");
        jPanel2.add(jLabel2);

        gameNumberSpinner.setPreferredSize(new java.awt.Dimension(89, 20));
        jPanel2.add(gameNumberSpinner);

        add(jPanel2);

        startGameButton.setText("Start game");
        add(startGameButton);
    }// </editor-fold>//GEN-END:initComponents

    private void playerNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerNameFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner gameNumberSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField playerNameField;
    private javax.swing.JButton startGameButton;
    // End of variables declaration//GEN-END:variables

    public int getGameID() {
        return (int) gameNumberSpinner.getValue();
    }
    
    public String getPlayerName()
    {
        return playerNameField.getText();
    }
}
